In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import numpy as np
import pandas as pd
import os
import seaborn as sns
import missingno as msno
import matplotlib.pyplot as plt
from datetime import datetime
import statsmodels.api as sm

In [ ]:
df_metdata2=pd.read_json(r'/content/drive/MyDrive/P_F_H/2.json',lines=True)
df_metdata2

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.127472e+20,Benjamin Vidot,1560405775843,5,Hot and cold sandwich's cold sodas and much mo...,None,None,0x89c2f48ae322c115:0xd28226c7ffc52291
1,1.048890e+20,Joel Bing,1558663754858,4,Nice environment cozy good food,None,None,0x89c2f48ae322c115:0xd28226c7ffc52291
2,1.063806e+20,Danny Ramos,1558467764714,5,Not good.,None,None,0x89c2f48ae322c115:0xd28226c7ffc52291
3,1.169573e+20,TRACY MITCHELL,1556481687751,3,Decent,None,None,0x89c2f48ae322c115:0xd28226c7ffc52291
4,1.084914e+20,Geovanni Rojas,1453077455490,1,(Translated by Google) Very unfortunate the ra...,None,None,0x89c2f48ae322c115:0xd28226c7ffc52291
...,...,...,...,...,...,...,...,...
149995,1.085485e+20,Komgrit Chukiert,1576891719351,4,None,None,None,0x89d9417bb8ab4d57:0x39a39051c7aa452f
149996,1.052827e+20,Widad IB,1517095258821,5,None,None,None,0x89d9417bb8ab4d57:0x39a39051c7aa452f
149997,1.137627e+20,John Wiswall,1549132248712,4,None,None,None,0x89d9417bb8ab4d57:0x39a39051c7aa452f
149998,1.145119e+20,Alex,1562050481023,5,None,None,None,0x89d9417bb8ab4d57:0x39a39051c7aa452f
149999,1.017314e+20,heather collins,1547305385010,1,None,None,None,0x89d9417bb8ab4d57:0x39a39051c7aa452f

In [ ]:
df_metdata3=pd.read_json(r'/content/drive/MyDrive/P_F_H/3.json',lines=True)
df_metdata3

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.121598e+20,Kevin Noble,1531531850612,4,Large electrical wholesaler with very good sto...,None,None,0x89d9f3c896fd648f:0x26e65f259859802f
1,1.120503e+20,Joseph Hanover,1471217722578,4,Good service and they know what those talking ...,None,None,0x89d9f3c896fd648f:0x26e65f259859802f
2,1.055255e+20,morice lee,1604339382504,4,Best,None,None,0x89d9f3c896fd648f:0x26e65f259859802f
3,1.112953e+20,Joe Milano,1544139014031,5,Excellant service and atmosphere,None,None,0x89d9f3c896fd648f:0x26e65f259859802f
4,1.037596e+20,Joe R,1552236266839,5,Has it all,None,None,0x89d9f3c896fd648f:0x26e65f259859802f
...,...,...,...,...,...,...,...,...
149995,1.081464e+20,Mya Rhodus,1531316168670,5,Real authentic back home food I absolutely lov...,None,None,0x89c25b60682deed3:0x3e007cd09ec0f0e5
149996,1.173153e+20,Juan Lopez,1521869879997,5,Great place great service friendly and respect...,None,None,0x89c25b60682deed3:0x3e007cd09ec0f0e5
149997,1.122765e+20,zin ski,1565202265454,5,"Excellent food, price and service!!!!",None,None,0x89c25b60682deed3:0x3e007cd09ec0f0e5
149998,1.042520e+20,Lorrianne Williams,1550577745823,5,Great guyanese food everyday.,None,None,0x89c25b60682deed3:0x3e007cd09ec0f0e5
149999,1.020725e+20,Gordon Reid,1532602773423,5,Good service and good food,None,None,0x89c25b60682deed3:0x3e007cd09ec0f0e5

In [ ]:
df_metdata4=pd.read_json(r'/content/drive/MyDrive/P_F_H/4.json',lines=True)
df_metdata4

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.121496e+20,Annette Green,1570882095310,4,The food is excellent,None,None,0x89c25b60682deed3:0x3e007cd09ec0f0e5
1,1.027794e+20,Yonette Hinds,1552593653693,5,Great tasting food.,None,None,0x89c25b60682deed3:0x3e007cd09ec0f0e5
2,1.167207e+20,Dennies G,1531254304902,5,Great food,None,None,0x89c25b60682deed3:0x3e007cd09ec0f0e5
3,1.149411e+20,Slimthick24 W,1544780492780,5,"Good, delicious food.",None,None,0x89c25b60682deed3:0x3e007cd09ec0f0e5
4,1.070571e+20,Nicola Hunte,1543697846703,4,Food very tasty,None,None,0x89c25b60682deed3:0x3e007cd09ec0f0e5
...,...,...,...,...,...,...,...,...
149995,1.058475e+20,Alanna Dolan,1534076526753,5,None,None,None,0x89c2c8dbefd938b5:0x9a069980fc47245
149996,1.050053e+20,Sixto Sinche,1620097082758,5,Very nice place food looks great taste great a...,None,None,0x89c25daf13bc726b:0x7f609addad46f073
149997,1.109932e+20,Ahmed Ali,1623284057992,5,David was very polite and professional\nWill d...,None,None,0x89c25daf13bc726b:0x7f609addad46f073
149998,1.023495e+20,I AM Crystal,1615329430120,5,Food was Amazing. Large portions family meal f...,None,None,0x89c25daf13bc726b:0x7f609addad46f073
149999,1.097423e+20,Candice Clarke,1614878108816,5,"The food is delicious, we ordered the family m...",None,None,0x89c25daf13bc726b:0x7f609addad46f073